"""GENERATED by drum-reducer-reference/tools/build_scorecard.py -- do not
hand-edit; re-run the tool to regenerate. Human-readable rendering of the
SURVIVE points tables + RELANE decision trees. See scorecard.json for the
machine-readable version this is generated from, and
DETERMINISM_CONTRACT.md Sec.4 for the decode semantics."""

QUANT_SCALE = 939.9201471292993

# ======================================================================
# SURVIVE / hard   base_points=-3554   T_tier=1
# decision: points >= T_tier  (pooled: sum(points) >= n * T_tier)
# ======================================================================
SURVIVE_HARD_BASE_POINTS = -3554
SURVIVE_HARD_T_TIER = 1
SURVIVE_HARD_POINTS = {
    # chord_size
    #         -inf <= x < 2.5        -> +597 pts
    #          2.5 <= x            -> +0 pts
    'chord_size': ([2.5], [597, 0]),
    # beat_in_measure
    #   constant, +0 pts (feature unused by the model)
    'beat_in_measure': ([], [0]),
    # beats_per_measure
    #   constant, +0 pts (feature unused by the model)
    'beats_per_measure': ([], [0]),
    # is_downbeat
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +141 pts
    'is_downbeat': ([0.5], [0, 141]),
    # local_density_500ms
    #         -inf <= x < 1.5        -> +345 pts
    #          1.5 <= x            -> +0 pts
    'local_density_500ms': ([1.5], [345, 0]),
    # gap_prev_ms
    #         -inf <= x < 167.4      -> +0 pts
    #        167.4 <= x            -> +19 pts
    'gap_prev_ms': ([167.3695000000007], [0, 19]),
    # gap_next_ms
    #         -inf <= x < 184.4      -> +0 pts
    #        184.4 <= x < 187.5      -> +86 pts
    #        187.5 <= x < 187.9      -> +164 pts
    #        187.9 <= x            -> +284 pts
    'gap_next_ms': ([184.3802499999947, 187.5, 187.92350000000442], [0, 86, 164, 284]),
    # ghost
    #   constant, +0 pts (feature unused by the model)
    'ghost': ([], [0]),
    # accent
    #   constant, +0 pts (feature unused by the model)
    'accent': ([], [0]),
    # flam
    #   constant, +0 pts (feature unused by the model)
    'flam': ([], [0]),
    # aligned_half
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +1158 pts
    'aligned_half': ([0.5], [0, 1158]),
    # aligned_quarter
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +292 pts
    'aligned_quarter': ([0.5], [0, 292]),
    # aligned_eighth
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +1458 pts
    'aligned_eighth': ([0.5], [0, 1458]),
    # lane_kick
    #         -inf <= x < 0.5        -> +1409 pts
    #          0.5 <= x            -> +0 pts
    'lane_kick': ([0.5], [1409, 0]),
    # lane_snare
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +358 pts
    'lane_snare': ([0.5], [0, 358]),
    # lane_hihat
    #   constant, +0 pts (feature unused by the model)
    'lane_hihat': ([], [0]),
    # lane_open-hat
    #   constant, +0 pts (feature unused by the model)
    'lane_open-hat': ([], [0]),
    # lane_high-tom
    #   constant, +0 pts (feature unused by the model)
    'lane_high-tom': ([], [0]),
    # lane_mid-tom
    #   constant, +0 pts (feature unused by the model)
    'lane_mid-tom': ([], [0]),
    # lane_floor-tom
    #   constant, +0 pts (feature unused by the model)
    'lane_floor-tom': ([], [0]),
    # lane_crash
    #   constant, +0 pts (feature unused by the model)
    'lane_crash': ([], [0]),
    # lane_ride
    #   constant, +0 pts (feature unused by the model)
    'lane_ride': ([], [0]),
    # lane_other
    #   constant, +0 pts (feature unused by the model)
    'lane_other': ([], [0]),
    # section_intro
    #   constant, +0 pts (feature unused by the model)
    'section_intro': ([], [0]),
    # section_outro
    #   constant, +0 pts (feature unused by the model)
    'section_outro': ([], [0]),
    # section_prechorus
    #   constant, +0 pts (feature unused by the model)
    'section_prechorus': ([], [0]),
    # section_chorus
    #   constant, +0 pts (feature unused by the model)
    'section_chorus': ([], [0]),
    # section_verse
    #   constant, +0 pts (feature unused by the model)
    'section_verse': ([], [0]),
    # section_bridge
    #   constant, +0 pts (feature unused by the model)
    'section_bridge': ([], [0]),
    # section_solo
    #   constant, +0 pts (feature unused by the model)
    'section_solo': ([], [0]),
    # section_breakdown
    #   constant, +0 pts (feature unused by the model)
    'section_breakdown': ([], [0]),
    # section_interlude
    #   constant, +0 pts (feature unused by the model)
    'section_interlude': ([], [0]),
    # section_fill
    #   constant, +0 pts (feature unused by the model)
    'section_fill': ([], [0]),
    # section_other
    #   constant, +0 pts (feature unused by the model)
    'section_other': ([], [0]),
    # era_RB1
    #   constant, +0 pts (feature unused by the model)
    'era_RB1': ([], [0]),
    # era_RB2
    #   constant, +0 pts (feature unused by the model)
    'era_RB2': ([], [0]),
    # era_RB3
    #   constant, +0 pts (feature unused by the model)
    'era_RB3': ([], [0]),
    # era_RB4
    #         -inf <= x < 0.5        -> +86 pts
    #          0.5 <= x            -> +0 pts
    'era_RB4': ([0.5], [86, 0]),
    # era_other
    #   constant, +0 pts (feature unused by the model)
    'era_other': ([], [0]),
    # chord_has_kick
    #   constant, +0 pts (feature unused by the model)
    'chord_has_kick': ([], [0]),
    # chord_has_snare
    #   constant, +0 pts (feature unused by the model)
    'chord_has_snare': ([], [0]),
    # chord_has_hihat
    #   constant, +0 pts (feature unused by the model)
    'chord_has_hihat': ([], [0]),
    # chord_has_open-hat
    #   constant, +0 pts (feature unused by the model)
    'chord_has_open-hat': ([], [0]),
    # chord_has_high-tom
    #   constant, +0 pts (feature unused by the model)
    'chord_has_high-tom': ([], [0]),
    # chord_has_mid-tom
    #   constant, +0 pts (feature unused by the model)
    'chord_has_mid-tom': ([], [0]),
    # chord_has_floor-tom
    #   constant, +0 pts (feature unused by the model)
    'chord_has_floor-tom': ([], [0]),
    # chord_has_crash
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +210 pts
    'chord_has_crash': ([0.5], [0, 210]),
    # chord_has_ride
    #   constant, +0 pts (feature unused by the model)
    'chord_has_ride': ([], [0]),
    # chord_has_other
    #   constant, +0 pts (feature unused by the model)
    'chord_has_other': ([], [0]),
    # aug_dist_backbone_ms
    #         -inf <= x < 185.2      -> +0 pts
    #        185.2 <= x < 191.2      -> +63 pts
    #        191.2 <= x < 198.7      -> +333 pts
    #        198.7 <= x            -> +403 pts
    'aug_dist_backbone_ms': ([185.18499999999767, 191.21549999999115, 198.67499999998836], [0, 63, 333, 403]),
    # aug_density_ratio
    #   constant, +0 pts (feature unused by the model)
    'aug_density_ratio': ([], [0]),
    # aug_samelane_prev_ms
    #         -inf <= x < 169.3      -> +0 pts
    #        169.3 <= x < 180.8      -> +118 pts
    #        180.8 <= x < 561.6      -> +515 pts
    #        561.6 <= x < 676.7      -> +554 pts
    #        676.7 <= x < 746.8      -> +609 pts
    #        746.8 <= x            -> +741 pts
    'aug_samelane_prev_ms': ([169.2685000000056, 180.8405000000057, 561.6239999999998, 676.7314999999944, 746.8020000000033], [0, 118, 515, 554, 609, 741]),
    # aug_samelane_next_ms
    #         -inf <= x < 191.4      -> +0 pts
    #        191.4 <= x < 193        -> +44 pts
    #          193 <= x < 194.5      -> +75 pts
    #        194.5 <= x < 275.9      -> +190 pts
    #        275.9 <= x < 600        -> +251 pts
    #          600 <= x < 616.4      -> +407 pts
    #        616.4 <= x < 678        -> +441 pts
    #          678 <= x            -> +557 pts
    'aug_samelane_next_ms': ([191.36449999999604, 193.00766666667187, 194.47900000000664, 275.86200000001554, 600.0, 616.4377499999973, 677.9619999999995], [0, 44, 75, 190, 251, 407, 441, 557]),
    # aug_chord_priority
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x < 1.5        -> +497 pts
    #          1.5 <= x            -> +1110 pts
    'aug_chord_priority': ([0.5, 1.5], [0, 497, 1110]),
    # aug_density_100ms
    #         -inf <= x < 1.5        -> +520 pts
    #          1.5 <= x            -> +0 pts
    'aug_density_100ms': ([1.5], [520, 0]),
    # aug_density_1500ms
    #         -inf <= x < 23.5       -> +87 pts
    #         23.5 <= x < 24.5       -> +23 pts
    #         24.5 <= x            -> +0 pts
    'aug_density_1500ms': ([23.5, 24.5], [87, 23, 0]),
    # aug_beat_frac
    #         -inf <= x < 5.684e-13  -> +163 pts
    #    5.684e-13 <= x            -> +0 pts
    'aug_beat_frac': ([5.684341886080801e-13], [163, 0]),
    # aug_lane_frac_500ms
    #         -inf <= x < 0.2247     -> +61 pts
    #       0.2247 <= x            -> +0 pts
    'aug_lane_frac_500ms': ([0.22474747474747475], [61, 0]),
}

# ======================================================================
# SURVIVE / medium   base_points=-4975   T_tier=0
# decision: points >= T_tier  (pooled: sum(points) >= n * T_tier)
# ======================================================================
SURVIVE_MEDIUM_BASE_POINTS = -4975
SURVIVE_MEDIUM_T_TIER = 0
SURVIVE_MEDIUM_POINTS = {
    # chord_size
    #         -inf <= x < 1.5        -> +0 pts
    #          1.5 <= x            -> +287 pts
    'chord_size': ([1.5], [0, 287]),
    # beat_in_measure
    #         -inf <= x < 3.833      -> +0 pts
    #        3.833 <= x < 4          -> +565 pts
    #            4 <= x            -> +623 pts
    'beat_in_measure': ([3.8333333333333712, 3.9999999999997726], [0, 565, 623]),
    # beats_per_measure
    #   constant, +0 pts (feature unused by the model)
    'beats_per_measure': ([], [0]),
    # is_downbeat
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +1440 pts
    'is_downbeat': ([0.5], [0, 1440]),
    # local_density_500ms
    #         -inf <= x < 1.5        -> +275 pts
    #          1.5 <= x            -> +0 pts
    'local_density_500ms': ([1.5], [275, 0]),
    # gap_prev_ms
    #   constant, +0 pts (feature unused by the model)
    'gap_prev_ms': ([], [0]),
    # gap_next_ms
    #         -inf <= x < 111.1      -> +0 pts
    #        111.1 <= x < 220.6      -> +82 pts
    #        220.6 <= x < 223.9      -> +150 pts
    #        223.9 <= x < 234.4      -> +212 pts
    #        234.4 <= x            -> +301 pts
    'gap_next_ms': ([111.11100000000442, 220.58799999998882, 223.8804999999993, 234.375], [0, 82, 150, 212, 301]),
    # ghost
    #   constant, +0 pts (feature unused by the model)
    'ghost': ([], [0]),
    # accent
    #   constant, +0 pts (feature unused by the model)
    'accent': ([], [0]),
    # flam
    #   constant, +0 pts (feature unused by the model)
    'flam': ([], [0]),
    # aligned_half
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +230 pts
    'aligned_half': ([0.5], [0, 230]),
    # aligned_quarter
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +1056 pts
    'aligned_quarter': ([0.5], [0, 1056]),
    # aligned_eighth
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +1552 pts
    'aligned_eighth': ([0.5], [0, 1552]),
    # lane_kick
    #         -inf <= x < 0.5        -> +2414 pts
    #          0.5 <= x            -> +0 pts
    'lane_kick': ([0.5], [2414, 0]),
    # lane_snare
    #   constant, +0 pts (feature unused by the model)
    'lane_snare': ([], [0]),
    # lane_hihat
    #   constant, +0 pts (feature unused by the model)
    'lane_hihat': ([], [0]),
    # lane_open-hat
    #   constant, +0 pts (feature unused by the model)
    'lane_open-hat': ([], [0]),
    # lane_high-tom
    #         -inf <= x < 0.5        -> +304 pts
    #          0.5 <= x            -> +0 pts
    'lane_high-tom': ([0.5], [304, 0]),
    # lane_mid-tom
    #   constant, +0 pts (feature unused by the model)
    'lane_mid-tom': ([], [0]),
    # lane_floor-tom
    #   constant, +0 pts (feature unused by the model)
    'lane_floor-tom': ([], [0]),
    # lane_crash
    #   constant, +0 pts (feature unused by the model)
    'lane_crash': ([], [0]),
    # lane_ride
    #   constant, +0 pts (feature unused by the model)
    'lane_ride': ([], [0]),
    # lane_other
    #   constant, +0 pts (feature unused by the model)
    'lane_other': ([], [0]),
    # section_intro
    #   constant, +0 pts (feature unused by the model)
    'section_intro': ([], [0]),
    # section_outro
    #   constant, +0 pts (feature unused by the model)
    'section_outro': ([], [0]),
    # section_prechorus
    #   constant, +0 pts (feature unused by the model)
    'section_prechorus': ([], [0]),
    # section_chorus
    #   constant, +0 pts (feature unused by the model)
    'section_chorus': ([], [0]),
    # section_verse
    #   constant, +0 pts (feature unused by the model)
    'section_verse': ([], [0]),
    # section_bridge
    #   constant, +0 pts (feature unused by the model)
    'section_bridge': ([], [0]),
    # section_solo
    #   constant, +0 pts (feature unused by the model)
    'section_solo': ([], [0]),
    # section_breakdown
    #   constant, +0 pts (feature unused by the model)
    'section_breakdown': ([], [0]),
    # section_interlude
    #   constant, +0 pts (feature unused by the model)
    'section_interlude': ([], [0]),
    # section_fill
    #   constant, +0 pts (feature unused by the model)
    'section_fill': ([], [0]),
    # section_other
    #   constant, +0 pts (feature unused by the model)
    'section_other': ([], [0]),
    # era_RB1
    #   constant, +0 pts (feature unused by the model)
    'era_RB1': ([], [0]),
    # era_RB2
    #   constant, +0 pts (feature unused by the model)
    'era_RB2': ([], [0]),
    # era_RB3
    #   constant, +0 pts (feature unused by the model)
    'era_RB3': ([], [0]),
    # era_RB4
    #   constant, +0 pts (feature unused by the model)
    'era_RB4': ([], [0]),
    # era_other
    #   constant, +0 pts (feature unused by the model)
    'era_other': ([], [0]),
    # chord_has_kick
    #   constant, +0 pts (feature unused by the model)
    'chord_has_kick': ([], [0]),
    # chord_has_snare
    #   constant, +0 pts (feature unused by the model)
    'chord_has_snare': ([], [0]),
    # chord_has_hihat
    #   constant, +0 pts (feature unused by the model)
    'chord_has_hihat': ([], [0]),
    # chord_has_open-hat
    #   constant, +0 pts (feature unused by the model)
    'chord_has_open-hat': ([], [0]),
    # chord_has_high-tom
    #   constant, +0 pts (feature unused by the model)
    'chord_has_high-tom': ([], [0]),
    # chord_has_mid-tom
    #   constant, +0 pts (feature unused by the model)
    'chord_has_mid-tom': ([], [0]),
    # chord_has_floor-tom
    #   constant, +0 pts (feature unused by the model)
    'chord_has_floor-tom': ([], [0]),
    # chord_has_crash
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +162 pts
    'chord_has_crash': ([0.5], [0, 162]),
    # chord_has_ride
    #   constant, +0 pts (feature unused by the model)
    'chord_has_ride': ([], [0]),
    # chord_has_other
    #   constant, +0 pts (feature unused by the model)
    'chord_has_other': ([], [0]),
    # aug_dist_backbone_ms
    #         -inf <= x < 230.3      -> +0 pts
    #        230.3 <= x < 236        -> +148 pts
    #          236 <= x            -> +253 pts
    'aug_dist_backbone_ms': ([230.3224999999802, 235.95850000000792], [0, 148, 253]),
    # aug_density_ratio
    #   constant, +0 pts (feature unused by the model)
    'aug_density_ratio': ([], [0]),
    # aug_samelane_prev_ms
    #         -inf <= x < 217.5      -> +0 pts
    #        217.5 <= x < 220.3      -> +183 pts
    #        220.3 <= x < 220.8      -> +303 pts
    #        220.8 <= x < 225.9      -> +351 pts
    #        225.9 <= x            -> +471 pts
    'aug_samelane_prev_ms': ([217.53900000000067, 220.33250000000044, 220.82750000003762, 225.89766666667128], [0, 183, 303, 351, 471]),
    # aug_samelane_next_ms
    #         -inf <= x < 221.4      -> +0 pts
    #        221.4 <= x < 226.3      -> +150 pts
    #        226.3 <= x < 234.4      -> +175 pts
    #        234.4 <= x            -> +194 pts
    'aug_samelane_next_ms': ([221.36874999999782, 226.33174999999756, 234.375], [0, 150, 175, 194]),
    # aug_chord_priority
    #   constant, +0 pts (feature unused by the model)
    'aug_chord_priority': ([], [0]),
    # aug_density_100ms
    #         -inf <= x < 1.5        -> +57 pts
    #          1.5 <= x            -> +0 pts
    'aug_density_100ms': ([1.5], [57, 0]),
    # aug_density_1500ms
    #         -inf <= x < 24.5       -> +69 pts
    #         24.5 <= x            -> +0 pts
    'aug_density_1500ms': ([24.5], [69, 0]),
    # aug_beat_frac
    #         -inf <= x < 5.684e-13  -> +248 pts
    #    5.684e-13 <= x < 1.364e-12  -> +72 pts
    #    1.364e-12 <= x            -> +0 pts
    'aug_beat_frac': ([5.684341886080801e-13, 1.3642420526593924e-12], [248, 72, 0]),
    # aug_lane_frac_500ms
    #         -inf <= x < 0.1623     -> +65 pts
    #       0.1623 <= x < 0.189      -> +31 pts
    #        0.189 <= x            -> +0 pts
    'aug_lane_frac_500ms': ([0.16228070175438597, 0.18898809523809523], [65, 31, 0]),
}

# ======================================================================
# SURVIVE / easy   base_points=-6511   T_tier=0
# decision: points >= T_tier  (pooled: sum(points) >= n * T_tier)
# ======================================================================
SURVIVE_EASY_BASE_POINTS = -6511
SURVIVE_EASY_T_TIER = 0
SURVIVE_EASY_POINTS = {
    # chord_size
    #         -inf <= x < 1.5        -> +0 pts
    #          1.5 <= x            -> +141 pts
    'chord_size': ([1.5], [0, 141]),
    # beat_in_measure
    #   constant, +0 pts (feature unused by the model)
    'beat_in_measure': ([], [0]),
    # beats_per_measure
    #   constant, +0 pts (feature unused by the model)
    'beats_per_measure': ([], [0]),
    # is_downbeat
    #   constant, +0 pts (feature unused by the model)
    'is_downbeat': ([], [0]),
    # local_density_500ms
    #         -inf <= x < 1.5        -> +200 pts
    #          1.5 <= x            -> +0 pts
    'local_density_500ms': ([1.5], [200, 0]),
    # gap_prev_ms
    #   constant, +0 pts (feature unused by the model)
    'gap_prev_ms': ([], [0]),
    # gap_next_ms
    #         -inf <= x < 113.9      -> +0 pts
    #        113.9 <= x < 120.5      -> +65 pts
    #        120.5 <= x < 124.4      -> +101 pts
    #        124.4 <= x < 225.6      -> +217 pts
    #        225.6 <= x < 234.4      -> +247 pts
    #        234.4 <= x            -> +269 pts
    'gap_next_ms': ([113.91199999999662, 120.48174999999173, 124.375, 225.5639999999985, 234.375], [0, 65, 101, 217, 247, 269]),
    # ghost
    #   constant, +0 pts (feature unused by the model)
    'ghost': ([], [0]),
    # accent
    #   constant, +0 pts (feature unused by the model)
    'accent': ([], [0]),
    # flam
    #   constant, +0 pts (feature unused by the model)
    'flam': ([], [0]),
    # aligned_half
    #   constant, +0 pts (feature unused by the model)
    'aligned_half': ([], [0]),
    # aligned_quarter
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +934 pts
    'aligned_quarter': ([0.5], [0, 934]),
    # aligned_eighth
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +1857 pts
    'aligned_eighth': ([0.5], [0, 1857]),
    # lane_kick
    #         -inf <= x < 0.5        -> +2921 pts
    #          0.5 <= x            -> +0 pts
    'lane_kick': ([0.5], [2921, 0]),
    # lane_snare
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +606 pts
    'lane_snare': ([0.5], [0, 606]),
    # lane_hihat
    #   constant, +0 pts (feature unused by the model)
    'lane_hihat': ([], [0]),
    # lane_open-hat
    #   constant, +0 pts (feature unused by the model)
    'lane_open-hat': ([], [0]),
    # lane_high-tom
    #         -inf <= x < 0.5        -> +201 pts
    #          0.5 <= x            -> +0 pts
    'lane_high-tom': ([0.5], [201, 0]),
    # lane_mid-tom
    #   constant, +0 pts (feature unused by the model)
    'lane_mid-tom': ([], [0]),
    # lane_floor-tom
    #   constant, +0 pts (feature unused by the model)
    'lane_floor-tom': ([], [0]),
    # lane_crash
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +699 pts
    'lane_crash': ([0.5], [0, 699]),
    # lane_ride
    #   constant, +0 pts (feature unused by the model)
    'lane_ride': ([], [0]),
    # lane_other
    #   constant, +0 pts (feature unused by the model)
    'lane_other': ([], [0]),
    # section_intro
    #   constant, +0 pts (feature unused by the model)
    'section_intro': ([], [0]),
    # section_outro
    #   constant, +0 pts (feature unused by the model)
    'section_outro': ([], [0]),
    # section_prechorus
    #   constant, +0 pts (feature unused by the model)
    'section_prechorus': ([], [0]),
    # section_chorus
    #   constant, +0 pts (feature unused by the model)
    'section_chorus': ([], [0]),
    # section_verse
    #         -inf <= x < 0.5        -> +185 pts
    #          0.5 <= x            -> +0 pts
    'section_verse': ([0.5], [185, 0]),
    # section_bridge
    #   constant, +0 pts (feature unused by the model)
    'section_bridge': ([], [0]),
    # section_solo
    #   constant, +0 pts (feature unused by the model)
    'section_solo': ([], [0]),
    # section_breakdown
    #   constant, +0 pts (feature unused by the model)
    'section_breakdown': ([], [0]),
    # section_interlude
    #   constant, +0 pts (feature unused by the model)
    'section_interlude': ([], [0]),
    # section_fill
    #   constant, +0 pts (feature unused by the model)
    'section_fill': ([], [0]),
    # section_other
    #   constant, +0 pts (feature unused by the model)
    'section_other': ([], [0]),
    # era_RB1
    #   constant, +0 pts (feature unused by the model)
    'era_RB1': ([], [0]),
    # era_RB2
    #   constant, +0 pts (feature unused by the model)
    'era_RB2': ([], [0]),
    # era_RB3
    #   constant, +0 pts (feature unused by the model)
    'era_RB3': ([], [0]),
    # era_RB4
    #         -inf <= x < 0.5        -> +0 pts
    #          0.5 <= x            -> +166 pts
    'era_RB4': ([0.5], [0, 166]),
    # era_other
    #   constant, +0 pts (feature unused by the model)
    'era_other': ([], [0]),
    # chord_has_kick
    #   constant, +0 pts (feature unused by the model)
    'chord_has_kick': ([], [0]),
    # chord_has_snare
    #   constant, +0 pts (feature unused by the model)
    'chord_has_snare': ([], [0]),
    # chord_has_hihat
    #   constant, +0 pts (feature unused by the model)
    'chord_has_hihat': ([], [0]),
    # chord_has_open-hat
    #   constant, +0 pts (feature unused by the model)
    'chord_has_open-hat': ([], [0]),
    # chord_has_high-tom
    #   constant, +0 pts (feature unused by the model)
    'chord_has_high-tom': ([], [0]),
    # chord_has_mid-tom
    #   constant, +0 pts (feature unused by the model)
    'chord_has_mid-tom': ([], [0]),
    # chord_has_floor-tom
    #   constant, +0 pts (feature unused by the model)
    'chord_has_floor-tom': ([], [0]),
    # chord_has_crash
    #   constant, +0 pts (feature unused by the model)
    'chord_has_crash': ([], [0]),
    # chord_has_ride
    #   constant, +0 pts (feature unused by the model)
    'chord_has_ride': ([], [0]),
    # chord_has_other
    #   constant, +0 pts (feature unused by the model)
    'chord_has_other': ([], [0]),
    # aug_dist_backbone_ms
    #         -inf <= x < 235.7      -> +0 pts
    #        235.7 <= x < 245.6      -> +79 pts
    #        245.6 <= x            -> +316 pts
    'aug_dist_backbone_ms': ([235.71924999999828, 245.58050000000367], [0, 79, 316]),
    # aug_density_ratio
    #   constant, +0 pts (feature unused by the model)
    'aug_density_ratio': ([], [0]),
    # aug_samelane_prev_ms
    #         -inf <= x < 225.6      -> +0 pts
    #        225.6 <= x < 231.6      -> +47 pts
    #        231.6 <= x < 235        -> +79 pts
    #          235 <= x < 236.2      -> +137 pts
    #        236.2 <= x < 247.9      -> +348 pts
    #        247.9 <= x            -> +546 pts
    'aug_samelane_prev_ms': ([225.56400000000576, 231.5699999999997, 235.00199999999677, 236.2204999999958, 247.93300000000454], [0, 47, 79, 137, 348, 546]),
    # aug_samelane_next_ms
    #         -inf <= x < 225.9      -> +0 pts
    #        225.9 <= x < 230.8      -> +37 pts
    #        230.8 <= x < 232.4      -> +81 pts
    #        232.4 <= x < 234.4      -> +136 pts
    #        234.4 <= x            -> +185 pts
    'aug_samelane_next_ms': ([225.92850000000908, 230.7674999999872, 232.41849999999977, 234.375], [0, 37, 81, 136, 185]),
    # aug_chord_priority
    #   constant, +0 pts (feature unused by the model)
    'aug_chord_priority': ([], [0]),
    # aug_density_100ms
    #   constant, +0 pts (feature unused by the model)
    'aug_density_100ms': ([], [0]),
    # aug_density_1500ms
    #   constant, +0 pts (feature unused by the model)
    'aug_density_1500ms': ([], [0]),
    # aug_beat_frac
    #         -inf <= x < 6.821e-13  -> +498 pts
    #    6.821e-13 <= x            -> +0 pts
    'aug_beat_frac': ([6.821210263296962e-13], [498, 0]),
    # aug_lane_frac_500ms
    #         -inf <= x < 0.1319     -> +275 pts
    #       0.1319 <= x < 0.1464     -> +209 pts
    #       0.1464 <= x < 0.1791     -> +176 pts
    #       0.1791 <= x < 0.189      -> +89 pts
    #        0.189 <= x < 0.2247     -> +22 pts
    #       0.2247 <= x < 0.9722     -> +0 pts
    #       0.9722 <= x            -> +54 pts
    'aug_lane_frac_500ms': ([0.1318840579710145, 0.1464285714285714, 0.17914438502673796, 0.18898809523809523, 0.22474747474747475, 0.9722222222222222], [275, 209, 176, 89, 22, 0, 54]),
}

# ======================================================================
# RELANE / hard / cymbal   lanes=['hihat', 'open-hat', 'crash', 'ride']
# returns (final_lane, confidence) where confidence = integer count margin
# ======================================================================
def relane_hard_cymbal(bin_index):
    # bin_index(feature_name) -> int, via relane_bin_edges + searchsorted(side='left')
    if bin_index('lane_hihat') <= 0:
        if bin_index('chord_has_crash') <= 0:
            return 'ride', 82529  # class_counts={'hihat': 9005, 'crash': 11503, 'ride': 94032}
        else:
            return 'crash', 65112  # class_counts={'hihat': 118, 'crash': 66769, 'ride': 1657}
    else:
        if bin_index('chord_has_crash') <= 0:
            return 'hihat', 261924  # class_counts={'hihat': 263904, 'crash': 1980, 'ride': 177}
        else:
            return 'crash', 4702  # class_counts={'hihat': 80, 'crash': 4974, 'ride': 272}

# ======================================================================
# RELANE / hard / tom   lanes=['high-tom', 'mid-tom', 'floor-tom']
# returns (final_lane, confidence) where confidence = integer count margin
# ======================================================================
def relane_hard_tom(bin_index):
    # bin_index(feature_name) -> int, via relane_bin_edges + searchsorted(side='left')
    if bin_index('lane_high-tom') <= 0:
        if bin_index('lane_floor-tom') <= 0:
            return 'mid-tom', 36889  # class_counts={'high-tom': 2523, 'mid-tom': 39412, 'floor-tom': 417}
        else:
            return 'floor-tom', 1929  # class_counts={'high-tom': 165, 'mid-tom': 9628, 'floor-tom': 11557}
    else:
        if bin_index('chord_has_mid-tom') <= 0:
            return 'high-tom', 42617  # class_counts={'high-tom': 43635, 'mid-tom': 1018, 'floor-tom': 204}
        else:
            return 'high-tom', 2487  # class_counts={'high-tom': 3296, 'mid-tom': 809, 'floor-tom': 6}

# ======================================================================
# RELANE / medium / cymbal   lanes=['hihat', 'open-hat', 'crash', 'ride']
# returns (final_lane, confidence) where confidence = integer count margin
# ======================================================================
def relane_medium_cymbal(bin_index):
    # bin_index(feature_name) -> int, via relane_bin_edges + searchsorted(side='left')
    if bin_index('lane_hihat') <= 0:
        if bin_index('chord_has_crash') <= 0:
            return 'ride', 64166  # class_counts={'hihat': 9791, 'crash': 11379, 'ride': 75545}
        else:
            return 'crash', 62269  # class_counts={'hihat': 361, 'crash': 63748, 'ride': 1479}
    else:
        if bin_index('chord_has_crash') <= 0:
            return 'hihat', 212298  # class_counts={'hihat': 213968, 'crash': 1670, 'ride': 113}
        else:
            return 'crash', 5052  # class_counts={'hihat': 49, 'crash': 5140, 'ride': 88}

# ======================================================================
# RELANE / medium / tom   lanes=['high-tom', 'mid-tom', 'floor-tom']
# returns (final_lane, confidence) where confidence = integer count margin
# ======================================================================
def relane_medium_tom(bin_index):
    # bin_index(feature_name) -> int, via relane_bin_edges + searchsorted(side='left')
    if bin_index('lane_high-tom') <= 0:
        if bin_index('chord_has_mid-tom') <= 0:
            return 'mid-tom', 295  # class_counts={'high-tom': 249, 'mid-tom': 6873, 'floor-tom': 6578}
        else:
            return 'mid-tom', 26262  # class_counts={'high-tom': 2685, 'mid-tom': 28947, 'floor-tom': 689}
    else:
        if bin_index('chord_has_mid-tom') <= 0:
            return 'high-tom', 24386  # class_counts={'high-tom': 25802, 'mid-tom': 1416, 'floor-tom': 169}
        else:
            return 'high-tom', 63  # class_counts={'high-tom': 1753, 'mid-tom': 1690, 'floor-tom': 3}

# ======================================================================
# RELANE / easy / cymbal   lanes=['hihat', 'open-hat', 'crash', 'ride']
# returns (final_lane, confidence) where confidence = integer count margin
# ======================================================================
def relane_easy_cymbal(bin_index):
    # bin_index(feature_name) -> int, via relane_bin_edges + searchsorted(side='left')
    if bin_index('lane_hihat') <= 0:
        if bin_index('chord_has_crash') <= 0:
            return 'ride', 51023  # class_counts={'hihat': 7088, 'crash': 10811, 'ride': 61834}
        else:
            return 'crash', 60453  # class_counts={'hihat': 95, 'crash': 61746, 'ride': 1293}
    else:
        if bin_index('chord_has_crash') <= 0:
            return 'hihat', 151616  # class_counts={'hihat': 153210, 'crash': 1594, 'ride': 141}
        else:
            return 'crash', 5036  # class_counts={'hihat': 47, 'crash': 5083, 'ride': 40}

# ======================================================================
# RELANE / easy / tom   lanes=['high-tom', 'mid-tom', 'floor-tom']
# returns (final_lane, confidence) where confidence = integer count margin
# ======================================================================
def relane_easy_tom(bin_index):
    # bin_index(feature_name) -> int, via relane_bin_edges + searchsorted(side='left')
    if bin_index('lane_high-tom') <= 0:
        if bin_index('chord_has_mid-tom') <= 0:
            return 'mid-tom', 492  # class_counts={'high-tom': 314, 'mid-tom': 5596, 'floor-tom': 5104}
        else:
            return 'mid-tom', 20974  # class_counts={'high-tom': 2301, 'mid-tom': 23275, 'floor-tom': 593}
    else:
        if bin_index('chord_has_mid-tom') <= 0:
            return 'high-tom', 18505  # class_counts={'high-tom': 19664, 'mid-tom': 1159, 'floor-tom': 146}
        else:
            return 'mid-tom', 501  # class_counts={'high-tom': 1312, 'mid-tom': 1813, 'floor-tom': 3}

