"""
Parity tests: drum_reducer's own featurize->model->decode path, run against
the frozen fixture in ../../data/fixtures/. Two things are being verified
at once:
  1. Every fixture song/tier's reduced note list matches byte-for-byte
     (note-for-note, (ms, lane) pairs, ms rounded to 3 decimals).
  2. The pooled rb4_test canonicalized edit_rate reproduces 0.1703 -- a
     hard drift guard.

The fixture was generated by a one-off build_fixture.py using THIS
package's own reduce() (no sklearn at generation time, only the packed
.bin files) -- so this test validates the shipped code path, not a
reimplementation of it.
"""
import json
import os
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
PKG_ROOT = os.path.dirname(HERE)
DATA_DIR = os.path.normpath(os.path.join(PKG_ROOT, "..", "data"))
sys.path.insert(0, PKG_ROOT)

from drum_reducer import editrate as ER  # noqa: E402
from drum_reducer import featurize  # noqa: E402
from drum_reducer import reduce as reduce_fn  # noqa: E402
from drum_reducer.backend_model import ModelBackend  # noqa: E402

FIXTURE_PATH = os.path.join(DATA_DIR, "fixtures", "parity_fixture.json")
CHARTS_DIR = os.path.join(DATA_DIR, "fixtures", "charts")
FEATURE_NAMES_PATH = os.path.join(DATA_DIR, "model", "feature_names.json")

RB4_TEST_POOLED_EDIT_RATE = 0.1703
TIERS = ["hard", "medium", "easy"]


@pytest.fixture(scope="module")
def model():
    return ModelBackend.load_default()


@pytest.fixture(scope="module")
def fixture():
    with open(FIXTURE_PATH) as f:
        return json.load(f)


def _load_chart(sid):
    with open(os.path.join(CHARTS_DIR, f"{sid}.json")) as f:
        return json.load(f)


def test_feature_names_match_ground_truth():
    with open(FEATURE_NAMES_PATH) as f:
        fn = json.load(f)
    assert featurize.FEATURE_NAMES == fn["feature_names"]
    assert len(featurize.FEATURE_NAMES) == 59
    # the deliberate duplicate column, reproduced exactly (see featurize.py docstring)
    assert featurize.FEATURE_NAMES.count("section_prechorus") == 2


def test_fixture_songs_match_note_for_note(model, fixture):
    songs = fixture["songs"]
    assert len(songs) > 0
    mismatches = []
    for sid, expected_by_tier in songs.items():
        chart = _load_chart(sid)
        for tier, expected in expected_by_tier.items():
            got = reduce_fn(chart, tier, model=model)
            got_rounded = [{"ms": round(n["ms"], 3), "lane": n["lane"]} for n in got]
            if got_rounded != expected:
                mismatches.append((sid, tier, len(expected), len(got_rounded)))
    assert not mismatches, f"{len(mismatches)} song/tier mismatches (first 10): {mismatches[:10]}"


def test_rb4_test_pooled_edit_rate(model, fixture):
    """The hard drift guard: pooled canonicalized edit_rate over the
    fixture's rb4_test songs must reproduce 0.1703 (+/- 1e-4)."""
    meta = fixture.get("metadata", {})
    n_rb4 = meta.get("n_rb4_test_songs")
    songs = fixture["songs"]
    edits_total, n_gt_total = 0, 0
    n_scored = 0
    for sid, expected_by_tier in songs.items():
        chart = _load_chart(sid)
        if chart.get("_edge_case"):
            continue  # synthetic edge cases aren't part of the rb4_test drift guard
        for tier in TIERS:
            gt_diff = chart["difficulties"].get(tier)
            gt = ER.notes_from_difficulty(gt_diff)
            if not gt:
                continue
            cand = reduce_fn(chart, tier, model=model)
            cand_notes = [ER.Note(n["ms"], n["lane"]) for n in cand]
            _rate, ops = ER.edit_rate(cand_notes, gt)
            edits_total += ops["insert"] + ops["delete"] + ops["lane_move"] + ops["slot_move"]
            n_gt_total += len(gt)
        n_scored += 1
    if n_rb4 is not None:
        assert n_scored == n_rb4, f"expected {n_rb4} rb4_test songs, scored {n_scored}"
    pooled = edits_total / n_gt_total
    print(f"\n[test_parity] rb4_test pooled canonicalized edit_rate = {pooled:.4f} "
          f"(n_songs={n_scored}, n_gt={n_gt_total})")
    assert abs(pooled - RB4_TEST_POOLED_EDIT_RATE) < 1e-4, (
        f"pooled edit_rate {pooled:.4f} drifted from the frozen reference {RB4_TEST_POOLED_EDIT_RATE}")


def test_edge_case_songs_run_without_error(model, fixture):
    """The synthetic edge-case songs (DETERMINISM_CONTRACT.md §6) just need
    to run cleanly through every tier -- their point is coverage, not a
    specific numeric target."""
    any_edge = False
    for sid in fixture["songs"]:
        chart = _load_chart(sid)
        if not chart.get("_edge_case"):
            continue
        any_edge = True
        for tier in TIERS:
            out = reduce_fn(chart, tier, model=model)
            assert isinstance(out, list)
    assert any_edge, "no synthetic edge-case songs found in the fixture"


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
